// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeAJmu1SmTYoqdf0-zPloe9TY19IHvG0g',
    appId: '1:917216489089:web:5a9f922b4d7c6b5862a780',
    messagingSenderId: '917216489089',
    projectId: 'trackbusbase',
    authDomain: 'trackbusbase.firebaseapp.com',
    storageBucket: 'trackbusbase.firebasestorage.app',
    measurementId: 'G-6JX4Q1H89B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnJFuPIq4-lpNDYSEU0irfIZQmOqZUBbo',
    appId: '1:917216489089:android:670ac9f64371983c62a780',
    messagingSenderId: '917216489089',
    projectId: 'trackbusbase',
    storageBucket: 'trackbusbase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDV-w7BBPqiZeiFR7iXJYO7_R0M6FpdGU',
    appId: '1:917216489089:ios:87c69796ec9dc10762a780',
    messagingSenderId: '917216489089',
    projectId: 'trackbusbase',
    storageBucket: 'trackbusbase.firebasestorage.app',
    iosBundleId: 'com.example.trackbus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDV-w7BBPqiZeiFR7iXJYO7_R0M6FpdGU',
    appId: '1:917216489089:ios:87c69796ec9dc10762a780',
    messagingSenderId: '917216489089',
    projectId: 'trackbusbase',
    storageBucket: 'trackbusbase.firebasestorage.app',
    iosBundleId: 'com.example.trackbus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeAJmu1SmTYoqdf0-zPloe9TY19IHvG0g',
    appId: '1:917216489089:web:03a8a74b6216819962a780',
    messagingSenderId: '917216489089',
    projectId: 'trackbusbase',
    authDomain: 'trackbusbase.firebaseapp.com',
    storageBucket: 'trackbusbase.firebasestorage.app',
    measurementId: 'G-ZXZX67V02V',
  );
}
